[workspace]
resolver = "2"
members=["src-tauri"]
default-members=["src-tauri"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
homepage = "https://cullify.ai/"
repository = "https://github.com/cullify/cullify.git"
description = "A Tauri App"
authors = ["Simon <fzpying@gmail.com>"]

[workspace.dependencies]
